### ISSUE TITLE
Action gives warning on set-output

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [Legorooj/skip-ci#2]
Hello

Action currently gives such warning, the set output mue be migrated to files approach.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by ievgenii-shepeliuk** [comment]
Hello @Legorooj 

As far as I understand the only change required is 

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Comment by Legorooj** [comment]
I'll take a look at this in a day or 2.

**Comment by Legorooj** [comment]
I've managed to fracture my wrist @ievgenii-shepeliuk so I can't program rn. If you're able to submit a PR I can probably merge it.

**Comment by ievgenii-shepeliuk** [comment]
> I've managed to fracture my wrist @ievgenii-shepeliuk so I can't program rn. If you're able to submit a PR I can probably merge it.

Hello @Legorooj 
Sorry to hear that, get well soon.
I can create a PR but since it's just a dependency update - I have no idea how I can test if it works or not. So, if you ok with this PR - I'll create it.

**Comment by Legorooj** [comment]
That sounds fine.

**Comment by ievgenii-shepeliuk** [comment]
Hello @Legorooj 

I hope you're doing better now.
Sorry, I was not able to create a PR as I've promised.
Are you able to take care about this issue now ?

**Comment by Legorooj** [comment]
Apologies, I completely forgot about this. The issues should now be resolved.
